### ISSUE TITLE
Regarding proper credit

### ISSUE THREAD

**Issue by lohanidamodar** [piyushsinha24/QuizAdda#4]
@piyushsinha24 It's ok that you have copied my repository which is shared under MIT License, and just changed colors and commits and made it as if your own. However you don't understand that in the App I am using opentdb.com API, which is shared under https://creativecommons.org/licenses/by-sa/4.0/ licence.

Based on both licenses, you must attribute both the Author and Opentdb.com in your APP.

**Comment by piyushsinha24** [comment]
Hello Sir, I did this way back while I was learning flutter & also had not much knowledge about the open source & license policies. I am sorry you had to reach out but really I had no such intentions & didn't monetize it at all. I am just a student & not much aware of these things. Please guide me what I need to do. I will be do the necessary.

**Comment by lohanidamodar** [comment]
@piyushsinha24 Include the MIT License, Attribute Opentdb.com and the original repository in your Github readme file as well as your published APP.

**Comment by piyushsinha24** [comment]
Readme updated & I will add the same in the published app.

**Comment by lohanidamodar** [comment]
Great! Keep learning! Good luck!
